{
  "nextId": 244,
  "arena": {
    "shape": "circle",
    "width": 600,
    "height": 600,
    "padding": 120,
    "grid": {
      "type": "rectangle",
      "rows": 1,
      "columns": 1
    }
  },
  "steps": [
    {
      "objects": [
        {
          "type": "rect",
          "color": "#8b57fa",
          "opacity": 60,
          "width": 300,
          "height": 600,
          "rotation": 0,
          "x": -151,
          "y": 0,
          "id": 1
        },
        {
          "type": "rect",
          "color": "#0066ff",
          "opacity": 55,
          "width": 300,
          "height": 600,
          "rotation": 0,
          "x": 150,
          "y": 0,
          "id": 2
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -177,
          "y": -19,
          "id": 3
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 121,
          "y": 46,
          "id": 4
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -108,
          "y": 98,
          "id": 5
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 71,
          "y": -6,
          "id": 6
        },
        {
          "orient": "point",
          "type": "polygon",
          "color": "#8b57fa",
          "opacity": 100,
          "radius": 50,
          "sides": 6,
          "rotation": 0,
          "x": -150,
          "y": 300,
          "id": 8
        },
        {
          "orient": "point",
          "type": "polygon",
          "color": "#0066ff",
          "opacity": 100,
          "radius": 50,
          "sides": 6,
          "rotation": 0,
          "x": 150,
          "y": 300,
          "id": 9
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215780_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Beyond Death",
          "iconId": 215780,
          "maxStacks": 0,
          "x": -106,
          "y": 128,
          "id": 10,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215590_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Allagan Field",
          "iconId": 215590,
          "maxStacks": 0,
          "x": 126,
          "y": 70,
          "id": 12
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215590_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Allagan Field",
          "iconId": 215590,
          "maxStacks": 0,
          "x": 76,
          "y": 20,
          "id": 13
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "Resolve debuffs\n\nOnce you're confidently in position:\n - Get ready for role stacks N/S\n - Check headmarker for spreads\n - Get ready for Motion/Stillness",
          "x": 28,
          "y": 247,
          "id": 14
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -94,
          "y": -72,
          "id": 15
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215590_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Allagan Field",
          "iconId": 215590,
          "maxStacks": 0,
          "x": -89,
          "y": -49,
          "id": 16
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -129,
          "y": 40,
          "id": 19
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215780_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Beyond Death",
          "iconId": 215780,
          "maxStacks": 0,
          "x": -127,
          "y": 70,
          "id": 20,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 67,
          "y": -81,
          "id": 21
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215590_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Allagan Field",
          "iconId": 215590,
          "maxStacks": 0,
          "x": 72,
          "y": -57,
          "id": 22
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -48,
          "y": 61,
          "id": 23
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215590_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Allagan Field",
          "iconId": 215590,
          "maxStacks": 0,
          "x": -46,
          "y": 82,
          "id": 25
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215590_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Allagan Field",
          "iconId": 215590,
          "maxStacks": 0,
          "x": -162,
          "y": 14,
          "id": 26
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/attack1.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Attack 1",
          "x": -151,
          "y": 4,
          "id": 48
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/attack2.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Attack 2",
          "x": 88,
          "y": 16,
          "id": 49
        }
      ]
    },
    {
      "objects": [
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -169,
          "y": 9,
          "id": 75
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -31,
          "y": -134,
          "id": 76
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -17,
          "y": 125,
          "id": 77
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 143,
          "y": -8,
          "id": 78
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "Resolve 1st Stack/Spreads\nDuring/After resolve, look for short Shrieks",
          "x": 3,
          "y": 314,
          "id": 84
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -4,
          "y": -122,
          "id": 89
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -6,
          "y": 128,
          "id": 91
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/attack1.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Attack 1",
          "x": -146,
          "y": 29,
          "id": 94
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/attack2.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Attack 2",
          "x": 169,
          "y": 22,
          "id": 95
        },
        {
          "type": "enemy",
          "icon": "none",
          "name": "",
          "color": "#ff0000",
          "opacity": 100,
          "radius": 79,
          "status": [],
          "rotation": 0,
          "ring": "dir",
          "x": 0,
          "y": 0,
          "id": 96
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 0,
          "y": 118,
          "id": 97
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -8,
          "y": -154,
          "id": 98
        },
        {
          "count": 1,
          "type": "stack",
          "color": "#ffc800",
          "opacity": 100,
          "radius": 75,
          "x": -1,
          "y": 11,
          "id": 99,
          "positionParentId": 97,
          "pinned": false
        },
        {
          "count": 1,
          "type": "stack",
          "color": "#ffc800",
          "opacity": 100,
          "radius": 75,
          "x": -8,
          "y": -122,
          "id": 100,
          "pinned": false
        },
        {
          "type": "circle",
          "color": "#fc972b",
          "opacity": 35,
          "radius": 84,
          "x": -169,
          "y": 7,
          "id": 101
        },
        {
          "type": "circle",
          "color": "#fc972b",
          "opacity": 35,
          "radius": 84,
          "x": 140,
          "y": -7,
          "id": 102
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "center",
          "fontSize": 55,
          "color": "#ffc800",
          "opacity": 100,
          "rotation": 0,
          "text": "!!!Respect Stillness/Motion!!!",
          "x": 25,
          "y": 249,
          "id": 227
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215696_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Compressed Water",
          "iconId": 215696,
          "maxStacks": 0,
          "x": -335,
          "y": 174,
          "id": 231
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215623_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Forked Lightning",
          "iconId": 215623,
          "maxStacks": 0,
          "x": -280,
          "y": 174,
          "id": 232
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215727_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Acceleration Bomb",
          "iconId": 215727,
          "maxStacks": 0,
          "x": -193,
          "y": 174,
          "id": 233
        }
      ]
    },
    {
      "objects": [
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 108,
          "y": 60,
          "id": 109
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -88,
          "y": -111,
          "id": 110
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 117,
          "y": 93,
          "id": 111
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -33,
          "y": -46,
          "id": 112
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "In/Off Line AoE\nShrieks in front, others behind\nEVERYONE look in or out depending on Gaze\n\nBe ready to stack middle after",
          "x": 1,
          "y": 290,
          "id": 113
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -73,
          "y": -87,
          "id": 114
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 89,
          "y": 89,
          "id": 115
        },
        {
          "type": "enemy",
          "icon": "none",
          "name": "",
          "color": "#ff0000",
          "opacity": 100,
          "radius": 79,
          "status": [],
          "rotation": 0,
          "ring": "dir",
          "x": 0,
          "y": 0,
          "id": 118
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 39,
          "y": 34,
          "id": 119
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -64,
          "y": -111,
          "id": 120
        },
        {
          "type": "line",
          "color": "#fc972b",
          "opacity": 35,
          "width": 167,
          "length": 600,
          "rotation": 45,
          "x": -153,
          "y": -273,
          "id": 129,
          "positionParentId": 118,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215588_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Cursed Shriek",
          "iconId": 215588,
          "maxStacks": 0,
          "x": -19,
          "y": -25,
          "id": 132,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215588_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Cursed Shriek",
          "iconId": 215588,
          "maxStacks": 0,
          "x": 55,
          "y": 55,
          "id": 133,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215588_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Cursed Shriek",
          "iconId": 215588,
          "maxStacks": 0,
          "x": -229,
          "y": 136,
          "id": 229,
          "pinned": false
        }
      ]
    },
    {
      "objects": [
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 1,
          "y": 2,
          "id": 134
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -1,
          "y": 7,
          "id": 135
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -11,
          "y": -5,
          "id": 136
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 0,
          "y": 6,
          "id": 137
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "Everyone stack middle to drop the first Element (Always Fire)\nCheck if it's \n- STAY (Donut) \n- MOVE (point blank, boss hitbox sized)\n\nMove out into role/spread spots",
          "x": 33,
          "y": 277,
          "id": 138
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -11,
          "y": 0,
          "id": 139
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 6,
          "y": -2,
          "id": 140
        },
        {
          "type": "enemy",
          "icon": "none",
          "name": "",
          "color": "#ff0000",
          "opacity": 100,
          "radius": 79,
          "status": [],
          "rotation": 0,
          "ring": "dir",
          "x": 0,
          "y": 0,
          "id": 141
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 9,
          "y": 6,
          "id": 142
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 0,
          "y": 2,
          "id": 143
        },
        {
          "type": "donut",
          "color": "#fc972b",
          "opacity": 35,
          "innerRadius": 84,
          "radius": 257,
          "x": 15,
          "y": 1,
          "id": 147,
          "positionParentId": 136,
          "pinned": false
        },
        {
          "type": "arrow",
          "color": "#ffffff",
          "opacity": 100,
          "width": 30,
          "length": 100,
          "arrowEnd": true,
          "rotation": 0,
          "x": 4,
          "y": 71,
          "id": 148
        },
        {
          "type": "arrow",
          "color": "#ffffff",
          "opacity": 100,
          "width": 30,
          "length": 100,
          "arrowEnd": true,
          "rotation": 90,
          "x": 94,
          "y": -5,
          "id": 149
        },
        {
          "type": "arrow",
          "color": "#ffffff",
          "opacity": 100,
          "width": 30,
          "length": 100,
          "arrowEnd": true,
          "rotation": 180,
          "x": 2,
          "y": -106,
          "id": 150
        },
        {
          "type": "arrow",
          "color": "#ffffff",
          "opacity": 100,
          "width": 30,
          "length": 100,
          "arrowEnd": true,
          "rotation": 270,
          "x": -100,
          "y": -7,
          "id": 151
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 3,
          "y": -67,
          "id": 152
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 4,
          "y": 58,
          "id": 153
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -61,
          "y": -3,
          "id": 154
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 74,
          "y": 0,
          "id": 155
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/ignore1.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Ignore 1",
          "x": -87,
          "y": 21,
          "id": 156
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/ignore2.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Ignore 2",
          "x": 85,
          "y": 24,
          "id": 158
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215902_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Entropy",
          "iconId": 215902,
          "maxStacks": 0,
          "x": -255,
          "y": 131,
          "id": 240
        }
      ]
    },
    {
      "objects": [
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -16,
          "y": -118,
          "id": 160
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -20,
          "y": 142,
          "id": 161
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 234,
          "y": -1,
          "id": 162
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "Resolve together with a real/fake cone",
          "x": -16,
          "y": 318,
          "id": 163
        },
        {
          "type": "enemy",
          "icon": "none",
          "name": "",
          "color": "#ff0000",
          "opacity": 100,
          "radius": 79,
          "status": [],
          "rotation": 0,
          "ring": "dir",
          "x": 0,
          "y": 0,
          "id": 166
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 0,
          "y": -151,
          "id": 174
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 3,
          "y": 152,
          "id": 175
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -211,
          "y": -4,
          "id": 176
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -7,
          "y": 108,
          "id": 177
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/ignore1.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Ignore 1",
          "x": -194,
          "y": 20,
          "id": 178
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "/marker/ignore2.png",
          "width": 40,
          "height": 40,
          "rotation": 0,
          "name": "Ignore 2",
          "x": 250,
          "y": 22,
          "id": 179
        },
        {
          "type": "cone",
          "color": "#f269ff",
          "opacity": 35,
          "radius": 300,
          "coneAngle": 90,
          "rotation": 45,
          "x": 0,
          "y": 0,
          "id": 180,
          "pinned": false
        },
        {
          "type": "cone",
          "color": "#f269ff",
          "opacity": 35,
          "radius": 300,
          "coneAngle": 90,
          "rotation": 225,
          "x": -2,
          "y": -1,
          "id": 181,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 16,
          "y": -121,
          "id": 182
        },
        {
          "count": 1,
          "type": "stack",
          "color": "#ffc800",
          "opacity": 100,
          "radius": 75,
          "x": 8,
          "y": 125,
          "id": 218,
          "pinned": false
        },
        {
          "count": 1,
          "type": "stack",
          "color": "#ffc800",
          "opacity": 100,
          "radius": 75,
          "x": 1,
          "y": -126,
          "id": 219,
          "pinned": false
        },
        {
          "type": "circle",
          "color": "#fc972b",
          "opacity": 35,
          "radius": 84,
          "x": -204,
          "y": -4,
          "id": 220
        },
        {
          "type": "circle",
          "color": "#fc972b",
          "opacity": 35,
          "radius": 84,
          "x": 221,
          "y": -6,
          "id": 221
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "center",
          "fontSize": 55,
          "color": "#ffc800",
          "opacity": 100,
          "rotation": 0,
          "text": "!!!Respect Stillness/Motion!!!",
          "x": 13,
          "y": 263,
          "id": 226
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215696_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Compressed Water",
          "iconId": 215696,
          "maxStacks": 0,
          "x": -315,
          "y": 187,
          "id": 234
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215623_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Forked Lightning",
          "iconId": 215623,
          "maxStacks": 0,
          "x": -260,
          "y": 187,
          "id": 235
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215727_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Acceleration Bomb",
          "iconId": 215727,
          "maxStacks": 0,
          "x": -180,
          "y": 187,
          "id": 236
        }
      ]
    },
    {
      "objects": [
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -10,
          "y": -106,
          "id": 183
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -23,
          "y": 133,
          "id": 184
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 1,
          "y": -50,
          "id": 185
        },
        {
          "type": "enemy",
          "icon": "none",
          "name": "",
          "color": "#ff0000",
          "opacity": 100,
          "radius": 79,
          "status": [],
          "rotation": 0,
          "ring": "dir",
          "x": 0,
          "y": 0,
          "id": 187
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 3,
          "y": -140,
          "id": 188
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 12,
          "y": 136,
          "id": 189
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -4,
          "y": 52,
          "id": 190
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -11,
          "y": 101,
          "id": 191
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 19,
          "y": -98,
          "id": 196
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215588_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Cursed Shriek",
          "iconId": 215588,
          "maxStacks": 0,
          "x": 12,
          "y": 66,
          "id": 197,
          "pinned": false
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215588_hr1.tex?format=png",
          "width": 24,
          "height": 32,
          "rotation": 0,
          "name": "Cursed Shriek",
          "iconId": 215588,
          "maxStacks": 0,
          "x": 21,
          "y": -34,
          "id": 198,
          "pinned": false
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "Resolve 2nd Shriek\nNo additional mechanic\n\nCheck 2nd Element",
          "x": 21,
          "y": 312,
          "id": 199
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215588_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Cursed Shriek",
          "iconId": 215588,
          "maxStacks": 0,
          "x": -228,
          "y": 131,
          "id": 230,
          "pinned": false
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "center",
          "fontSize": 30,
          "color": "#ffc800",
          "opacity": 100,
          "rotation": 0,
          "text": "!!Engage all your braincells \nto start solving the stored mech!!",
          "x": 28,
          "y": 223,
          "id": 242
        }
      ]
    },
    {
      "objects": [
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -11,
          "y": -4,
          "id": 200
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -7,
          "y": 22,
          "id": 201
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -3,
          "y": -10,
          "id": 202
        },
        {
          "type": "enemy",
          "icon": "none",
          "name": "",
          "color": "#ff0000",
          "opacity": 100,
          "radius": 79,
          "status": [],
          "rotation": 0,
          "ring": "dir",
          "x": 0,
          "y": 0,
          "id": 203
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 0,
          "y": -8,
          "id": 204
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 4,
          "y": 23,
          "id": 205
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 20,
          "y": -4,
          "id": 206
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/support.png",
          "name": "Support",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": -7,
          "y": 19,
          "id": 207
        },
        {
          "opacity": 100,
          "type": "party",
          "image": "/actor/dps.png",
          "name": "DPS",
          "status": [],
          "width": 40,
          "height": 40,
          "rotation": 0,
          "x": 13,
          "y": 10,
          "id": 208
        },
        {
          "stroke": "#000000",
          "style": "outline",
          "type": "text",
          "align": "left",
          "fontSize": 25,
          "color": "#ffffff",
          "opacity": 100,
          "rotation": 0,
          "text": "Stored Mech + 2nd Element (Always Water)\nStack middle to drop Fire/Water\n\nFind safe spot inside or outside\ndepending on Donut or cHaRiOT 🤓☝️",
          "x": 39,
          "y": 302,
          "id": 211
        },
        {
          "type": "circle",
          "color": "#fc972b",
          "opacity": 70,
          "radius": 91,
          "x": 0,
          "y": 0,
          "id": 212
        },
        {
          "type": "line",
          "color": "#bf00ff",
          "opacity": 80,
          "width": 167,
          "length": 600,
          "rotation": 45,
          "x": -151,
          "y": -276,
          "id": 213,
          "pinned": false
        },
        {
          "type": "cone",
          "color": "#f269ff",
          "opacity": 50,
          "radius": 300,
          "coneAngle": 90,
          "rotation": 45,
          "x": 0,
          "y": 0,
          "id": 214,
          "pinned": false
        },
        {
          "type": "cone",
          "color": "#f269ff",
          "opacity": 50,
          "radius": 300,
          "coneAngle": 90,
          "rotation": 225,
          "x": 0,
          "y": 0,
          "id": 215,
          "pinned": false
        },
        {
          "type": "line",
          "color": "#bf00ff",
          "opacity": 65,
          "width": 167,
          "length": 600,
          "rotation": 45,
          "x": -388,
          "y": -39,
          "id": 217,
          "pinned": false,
          "positionParentId": 203
        },
        {
          "opacity": 100,
          "type": "icon",
          "image": "https://v2.xivapi.com/api/asset/ui/icon/215000/215903_hr1.tex?format=png",
          "width": 60,
          "height": 80,
          "rotation": 0,
          "name": "Dynamic Fluid",
          "iconId": 215903,
          "maxStacks": 0,
          "x": -222,
          "y": 170,
          "id": 237
        }
      ]
    }
  ]
}
